### PR TITLE
Added --install_mode option

### PR DESCRIPTION
**Pull request by wouterdb**
did not add testcases, as this would be quite complex compared to the functionality

### CODE REVIEW

**Comment by arnaudsjs** [comment]
Open question: If an incorrect value is provided to the `install_mode` option, due to a typo. It will result in a warning but not a hard failure. Is this desired behavior for pytest-inmanta? Do we need to change this into a hard failure?

**Comment by wouterdb** [comment]
I have asked myself the same question. 

@bartv wdyt?

**Comment by bartv** [comment]
I prefer a hard fail as well

**Comment by wouterdb** [comment]
@arnaudsjs I added a hard failure on bad options

**Pull request merged**
